//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessData
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 字典目录
    /// </summary>
    public partial class CONSTCLS
    {
        /// <summary>
        /// 
        /// </summary>
        public int MBBSM { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> CONSTSLSID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CONSTCLSNAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CONSTCLSTYPE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BZ { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> CREATETIME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
    }
}
