//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessData
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 字典
    /// </summary>
    public partial class CONST
    {
        /// <summary>
        /// 
        /// </summary>
        public int MBBSM { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> CONSTSLSID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CONSTVALUE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CONSTTRANS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> PARENTNODE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> CONSTORDER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BZ { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> CREATETIME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string REPORTVALUE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GJCONSTTRANS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SFSY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GJVALUE { get; set; }
    }
}
