//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessData
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 层
    /// </summary>
    public partial class Floor
    {
        /// <summary>
        /// ID
        /// </summary>
        public System.Guid ID { get; set; }
        /// <summary>
        /// 项目ID
        /// </summary>
        public System.Guid ProjectID { get; set; }
        /// <summary>
        /// 层号
        /// </summary>
        public string CH { get; set; }
        /// <summary>
        /// 自然幢号
        /// </summary>
        public string ZRZH { get; set; }
        /// <summary>
        /// 要素代码
        /// </summary>
        public string YSDM { get; set; }
        /// <summary>
        /// 实际层
        /// </summary>
        public string SJC { get; set; }
        /// <summary>
        /// 名义层
        /// </summary>
        public string MYC { get; set; }
        /// <summary>
        /// 层建筑面积
        /// </summary>
        public string CJZMJ { get; set; }
        /// <summary>
        /// 层套内建筑面积
        /// </summary>
        public string CTNJZMJ { get; set; }
        /// <summary>
        /// 层阳台面积
        /// </summary>
        public string CYTMJ { get; set; }
        /// <summary>
        /// 层共有建筑面积
        /// </summary>
        public string CGYJZMJ { get; set; }
        /// <summary>
        /// 层分摊建筑面积
        /// </summary>
        public string CFTJZMJ { get; set; }
        /// <summary>
        /// 层半墙面积
        /// </summary>
        public string CBQMJ { get; set; }
        /// <summary>
        /// 层高
        /// </summary>
        public string CG { get; set; }
        /// <summary>
        /// 水平投影面积
        /// </summary>
        public string SPTYMJ { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public System.DateTime UpdateTime { get; set; }
    }
}
