//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessData
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 自然幢
    /// </summary>
    public partial class NaturalBuilding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NaturalBuilding()
        {
            this.LogicalBuildings = new HashSet<LogicalBuilding>();
            this.Floors = new HashSet<Floor>();
            this.Households = new HashSet<Household>();
        }
    
        /// <summary>
        /// ID
        /// </summary>
        public System.Guid ID { get; set; }
        /// <summary>
        /// 项目ID
        /// </summary>
        public System.Guid ProjectID { get; set; }
        /// <summary>
        /// 标识码
        /// </summary>
        public string BSM { get; set; }
        /// <summary>
        /// 要素代码
        /// </summary>
        public string YSDM { get; set; }
        /// <summary>
        /// 不动产单元号
        /// </summary>
        public string BDCDYH { get; set; }
        /// <summary>
        /// 宗地代码
        /// </summary>
        public string ZDDM { get; set; }
        /// <summary>
        /// 自然幢号
        /// </summary>
        public string ZRZH { get; set; }
        /// <summary>
        /// 项目名称
        /// </summary>
        public string XMMC { get; set; }
        /// <summary>
        /// 建筑物名称
        /// </summary>
        public string JZWMC { get; set; }
        /// <summary>
        /// 竣工日期
        /// </summary>
        public Nullable<System.DateTime> JGRQ { get; set; }
        /// <summary>
        /// 建筑物高度
        /// </summary>
        public Nullable<double> JZWGD { get; set; }
        /// <summary>
        /// 幢占地面积
        /// </summary>
        public double ZZDMJ { get; set; }
        /// <summary>
        /// 幢用地面积
        /// </summary>
        public double ZYDMJ { get; set; }
        /// <summary>
        /// 预测建筑面积
        /// </summary>
        public Nullable<double> YCJZMJ { get; set; }
        /// <summary>
        /// 实测建筑面积
        /// </summary>
        public Nullable<double> SCJZMJ { get; set; }
        /// <summary>
        /// 总层数
        /// </summary>
        public int ZCS { get; set; }
        /// <summary>
        /// 地上层数
        /// </summary>
        public int DSCS { get; set; }
        /// <summary>
        /// 地下层数
        /// </summary>
        public int DXCS { get; set; }
        /// <summary>
        /// 地下深度
        /// </summary>
        public Nullable<double> DXSD { get; set; }
        /// <summary>
        /// 规划用途
        /// </summary>
        public string GHYT { get; set; }
        /// <summary>
        /// 房屋结构
        /// </summary>
        public int FWJG { get; set; }
        /// <summary>
        /// 总套数
        /// </summary>
        public int ZTS { get; set; }
        /// <summary>
        /// 建筑物基本用途
        /// </summary>
        public string JZWJBYT { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        public int ZT { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string BZ { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Project Project { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogicalBuilding> LogicalBuildings { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Floor> Floors { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Household> Households { get; set; }
    }
}
