//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessData
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 查封信息
    /// </summary>
    public partial class Sequestration
    {
        /// <summary>
        /// 
        /// </summary>
        public System.Guid ID { get; set; }
        /// <summary>
        /// 项目编号
        /// </summary>
        public System.Guid ProjectID { get; set; }
        /// <summary>
        /// 户标识码
        /// </summary>
        public string HBSM { get; set; }
        /// <summary>
        /// 查封机关
        /// </summary>
        public string CFJG { get; set; }
        /// <summary>
        /// 查封类型
        /// </summary>
        public string CFLX { get; set; }
        /// <summary>
        /// 查封文件
        /// </summary>
        public string CFWJ { get; set; }
        /// <summary>
        /// 查封文号
        /// </summary>
        public string CFWH { get; set; }
        /// <summary>
        /// 解封文件
        /// </summary>
        public string JFWJ { get; set; }
        /// <summary>
        /// 解封文号
        /// </summary>
        public string JFWH { get; set; }
        /// <summary>
        /// 查封起始时间
        /// </summary>
        public Nullable<System.DateTime> CFQSSJ { get; set; }
        /// <summary>
        /// 查封结束时间
        /// </summary>
        public Nullable<System.DateTime> CFJSSJ { get; set; }
        /// <summary>
        /// 登记时间
        /// </summary>
        public Nullable<System.DateTime> DJSJ { get; set; }
        /// <summary>
        /// 登簿人
        /// </summary>
        public string DBR { get; set; }
        /// <summary>
        /// 轮候次序
        /// </summary>
        public string LHCX { get; set; }
        /// <summary>
        /// 查封时间
        /// </summary>
        public System.DateTime CFSJ { get; set; }
        /// <summary>
        /// 附记
        /// </summary>
        public string FJ { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public System.DateTime UpdateTime { get; set; }
    }
}
