//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicOfferSystem
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 申请人
    /// </summary>
    public partial class Applicant
    {
        /// <summary>
        /// ID
        /// </summary>
        public System.Guid ID { get; set; }
        /// <summary>
        /// 项目ID
        /// </summary>
        public System.Guid ProjectID { get; set; }
        /// <summary>
        /// 不动产单元号
        /// </summary>
        public string BDCDYH { get; set; }
        /// <summary>
        /// 不动产权证号
        /// </summary>
        public string BDCQZH { get; set; }
        /// <summary>
        /// 申请人姓名
        /// </summary>
        public string SQRXM { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        public string XB { get; set; }
        /// <summary>
        /// 证件类型
        /// </summary>
        public string ZJLX { get; set; }
        /// <summary>
        /// 证件类型名称
        /// </summary>
        public string ZJLXMC { get; set; }
        /// <summary>
        /// 证件号
        /// </summary>
        public string ZJH { get; set; }
        /// <summary>
        /// 发证机关
        /// </summary>
        public string FZJG { get; set; }
        /// <summary>
        /// 国家地区
        /// </summary>
        public string GJDQ { get; set; }
        /// <summary>
        /// 户籍所在省市
        /// </summary>
        public string HJSZSS { get; set; }
        /// <summary>
        /// 工作单位
        /// </summary>
        public string GZDW { get; set; }
        /// <summary>
        /// 所属行业
        /// </summary>
        public string SSHY { get; set; }
        /// <summary>
        /// 联系电话
        /// </summary>
        public string LXDH { get; set; }
        /// <summary>
        /// 通讯地址
        /// </summary>
        public string TXDZ { get; set; }
        /// <summary>
        /// 邮政编码
        /// </summary>
        public string YZBM { get; set; }
        /// <summary>
        /// 电子邮件
        /// </summary>
        public string DZYJ { get; set; }
        /// <summary>
        /// 法人姓名
        /// </summary>
        public string FRXM { get; set; }
        /// <summary>
        /// 法人证件类型
        /// </summary>
        public string FRZJLX { get; set; }
        /// <summary>
        /// 法人电话
        /// </summary>
        public string FRDH { get; set; }
        /// <summary>
        /// 申请人类型
        /// </summary>
        public string SQRLX { get; set; }
        /// <summary>
        /// 申请人类型名称
        /// </summary>
        public string SQRLXMC { get; set; }
        /// <summary>
        /// 代理人姓名
        /// </summary>
        public string DLRXM { get; set; }
        /// <summary>
        /// 代理机构名称
        /// </summary>
        public string DLJGMC { get; set; }
        /// <summary>
        /// 代理人电话
        /// </summary>
        public string DLRDH { get; set; }
        /// <summary>
        /// 有效标志
        /// </summary>
        public string YXBZ { get; set; }
        /// <summary>
        /// 共有方式
        /// </summary>
        public string GYFS { get; set; }
        /// <summary>
        /// 申请人类别
        /// </summary>
        public string SQRLB { get; set; }
        /// <summary>
        /// 申请人类别名称
        /// </summary>
        public string SQRLBMC { get; set; }
        /// <summary>
        /// 是否持证人
        /// </summary>
        public string SFCZR { get; set; }
        /// <summary>
        /// 不动产单元类型
        /// </summary>
        public string BDCDYLX { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
