//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicOfferSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogicalBuilding
    {
        public System.Guid ID { get; set; }
        public System.Guid ProjectID { get; set; }
        public System.Guid NaturalBuildingID { get; set; }
        public string LJZH { get; set; }
        public string ZRZH { get; set; }
        public string YSDM { get; set; }
        public string MPH { get; set; }
        public double YCJZMJ { get; set; }
        public double YCDXMJ { get; set; }
        public double YCQTMJ { get; set; }
        public double SCJZMJ { get; set; }
        public double SCDXMJ { get; set; }
        public double SCQTMJ { get; set; }
        public System.DateTime JGRQ { get; set; }
        public string FWJG1 { get; set; }
        public string FWJG2 { get; set; }
        public string FWJG3 { get; set; }
        public string JZWZT { get; set; }
        public int ZCS { get; set; }
        public int DSCS { get; set; }
        public int DXCS { get; set; }
        public string BZ { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual NaturalBuilding NaturalBuilding { get; set; }
    }
}
