//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicOfferSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obligee
    {
        public System.Guid ID { get; set; }
        public System.Guid ProjectID { get; set; }
        public string HBSM { get; set; }
        public string QLRMC { get; set; }
        public string BDCQZH { get; set; }
        public int ZJZL { get; set; }
        public string ZJH { get; set; }
        public int GJ { get; set; }
        public int XB { get; set; }
        public string QLRLX { get; set; }
        public string DH { get; set; }
        public string YB { get; set; }
        public string DZ { get; set; }
        public int QLLX { get; set; }
        public int GYFS { get; set; }
        public double QLMJ { get; set; }
        public string QLBL { get; set; }
        public string FRXM { get; set; }
        public int FRZJLX { get; set; }
        public string FRZJH { get; set; }
        public string FRDH { get; set; }
        public string DLRXM { get; set; }
        public int DLRZJLX { get; set; }
        public string DLRZJH { get; set; }
        public string DLRDH { get; set; }
        public string GZDW { get; set; }
        public string DLJGMC { get; set; }
        public string DZYJ { get; set; }
        public string BZ { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
