//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicOfferSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Household
    {
        public System.Guid ID { get; set; }
        public System.Guid ProjectID { get; set; }
        public System.Guid NaturalBuildingID { get; set; }
        public string HBSM { get; set; }
        public string YXTBS { get; set; }
        public string BDCDYH { get; set; }
        public string FWBM { get; set; }
        public string YSDM { get; set; }
        public string ZRZH { get; set; }
        public string LJZH { get; set; }
        public string DYH { get; set; }
        public int ZCS { get; set; }
        public string CH { get; set; }
        public string FH { get; set; }
        public string ZL { get; set; }
        public int MJDW { get; set; }
        public string SZC { get; set; }
        public string QSC { get; set; }
        public string ZZC { get; set; }
        public string HH { get; set; }
        public string SHBW { get; set; }
        public int HX { get; set; }
        public int HXJG { get; set; }
        public string GHYT { get; set; }
        public int FWYT1 { get; set; }
        public int FWYT2 { get; set; }
        public int FWYT3 { get; set; }
        public double YCJZMJ { get; set; }
        public double YCTNJZMJ { get; set; }
        public double YCFTJZMJ { get; set; }
        public double YCDXBFJZMJ { get; set; }
        public double YCQTJZMJ { get; set; }
        public string YCFTXS { get; set; }
        public double SCJZMJ { get; set; }
        public double SCTNJZMJ { get; set; }
        public double SCFTJZMJ { get; set; }
        public double SCDXBFJZMJ { get; set; }
        public double SCQTJZMJ { get; set; }
        public string SCFTXS { get; set; }
        public double GYTDMJ { get; set; }
        public double FTTDMJ { get; set; }
        public double DYTDMJ { get; set; }
        public int FWLX { get; set; }
        public int FWJG { get; set; }
        public int FWXZ { get; set; }
        public int FWCB { get; set; }
        public double FDCJYJG { get; set; }
        public System.DateTime JGSJ { get; set; }
        public string CQLY { get; set; }
        public string QTGSD { get; set; }
        public string QTGSN { get; set; }
        public string QTGSX { get; set; }
        public string QTGSB { get; set; }
        public string TDSYQR { get; set; }
        public string FCFHT { get; set; }
        public int ZT { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual NaturalBuilding NaturalBuilding { get; set; }
    }
}
