//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectronicOfferSystemDBContainer : DbContext
    {
        public ElectronicOfferSystemDBContainer()
            : base("name=ElectronicOfferSystemDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> ProjectSet { get; set; }
        public virtual DbSet<NaturalBuilding> NaturalBuildingSet { get; set; }
        public virtual DbSet<LogicalBuilding> LogicalBuildingSet { get; set; }
        public virtual DbSet<Floor> FloorSet { get; set; }
        public virtual DbSet<Obligee> ObligeeSet { get; set; }
        public virtual DbSet<Household> HouseholdSet { get; set; }
    }
}
